version: '3.7'
services:
  api:
    container_name: 'api'
    build: './'
    ports:
      - '9000:9000'
    environment:
      - MONGO_URI
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo_chat'
    ports:
      - '27017:27017'